[package]
    name = "sorted-tf-idf-list"
    version = "0.1.0"
    edition = "2021"

[dependencies]
    pbr = "1.0"
    serde = "1.0.117"
    serde_derive = "1.0.117"
    serde_json = "1.0.59"

[dependencies.clap]
    version = "4.0"
    features = ["derive"]
